// Generated by https://quicktype.io

export interface PCItem {
  id: number;
  productionQuantity: number;
  fixedCost: number;
  variableCost: number;
  totalCost: number;
  marginalCost: number;
  createdAt: string;
  updatedAt: string;
}

export default PCItem;
